name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: golangci/golangci-lint-action@master
      - run: go test -v -race -cover ./... -coverprofile=coverage.out
      - run: .github/build.sh
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
      - uses: jandelgado/gcov2lcov-action@v1.0.5
      - uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov