name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
      - name: Coverage
        run: go test -v -race -cover ./...
      - name: Build
        run: |
          set -x
          mkdir -p build
          GOOS=linux  go build -a -ldflags "-s -w" -o build/smpp-receiver-linux-amd64 ./cmd/smpp-receiver
          GOOS=linux  go build -a -ldflags "-s -w" -o build/smpp-repl-linux-amd64     ./cmd/smpp-repl
          GOOS=darwin go build -a -ldflags "-s -w" -o build/smpp-repl-darwin-amd64    ./cmd/smpp-repl
          upx build/*
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build