name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: golangci/golangci-lint-action@master
      - run: go test -v -race -cover ./... -coverprofile=coverage.out
      - run: GOOS=linux go build -o smpp-receiver-linux-amd64 ./cmd/smpp-receiver
      - uses: actions/upload-artifact@v2
        with:
          path: smpp-receiver-linux-amd64
      - run: GOOS=linux go build -o smpp-repl-linux-amd64 ./cmd/smpp-repl
      - uses: actions/upload-artifact@v2
        with:
          path: smpp-repl-linux-amd64
      - run: GOOS=linux go build -o smpp-repl-darwin-amd64 ./cmd/smpp-repl
      - uses: actions/upload-artifact@v2
        with:
          path: smpp-repl-darwin-amd64
      - uses: jandelgado/gcov2lcov-action@v1.0.5
      - uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov