name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
      - name: Coverage
        run: go test -v -race -cover ./...
      - name: Generate build files (smpp-receiver)
        uses: crazy-max/ghaction-xgo@v1
        with:
          pkg: cmd/smpp-receiver
          prefix: smpp-receiver
          targets: linux/amd64,darwin/amd64
          ldflags: -s -w
      - name: Generate build files (smpp-repl)
        uses: crazy-max/ghaction-xgo@v1
        with:
          pkg: cmd/smpp-repl
          prefix: smpp-repl
          targets: linux/amd64,darwin/amd64
          ldflags: -s -w
      - name: Compression (UPX)
        run: upx build/*
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build